import type { Metadata } from "next";
import type { LucideIcon } from "lucide-react";
import {
  AlarmClock,
  AppWindow,
  ArrowDownAZ,
  AudioLines,
  Binary,
  Blend,
  Braces,
  Cake,
  CalendarClock,
  CalendarRange,
  Camera,
  Clock,
  CodeXml,
  Contrast,
  Crop,
  Dices,
  Diff,
  Earth,
  EyeOff,
  FileAudio,
  FileCode,
  FileDigit,
  FileImage,
  FileJson,
  FileLock,
  FilePen,
  FileText,
  Film,
  Fingerprint,
  Gamepad2,
  Gauge,
  Globe,
  Hash,
  HeartPulse,
  Images,
  Keyboard,
  KeyRound,
  Landmark,
  Layers,
  Link2,
  LinkIcon,
  LockKeyhole,
  Mic,
  Monitor,
  MonitorSmartphone,
  Mouse,
  MousePointerClick,
  Network,
  Palette,
  Percent,
  PenLine,
  Pilcrow,
  Pipette,
  QrCode,
  Radio,
  Ratio,
  Receipt,
  Regex,
  Replace,
  Ruler,
  Scaling,
  Scroll,
  SearchCode,
  Server,
  Sheet,
  Shrink,
  Shuffle,
  Sigma,
  Sparkles,
  SwatchBook,
  Target,
  TextCursorInput,
  Timer,
  Type,
  Volume2,
  Zap,
} from "lucide-react";
import {
  IMAGE_CONVERSIONS,
  IMAGE_FORMATS,
  SOURCE_FORMAT_LABELS,
  conversionSlug,
} from "@/lib/image-formats";
import { SITE_NAME, SITE_URL } from "@/lib/site";

export type ToolCategoryId =
  | "media"
  | "developer"
  | "text"
  | "generators"
  | "calculators"
  | "design"
  | "time"
  | "device"
  | "network";

export type ToolCategory = { id: ToolCategoryId; name: string; description: string };

export const TOOL_CATEGORIES: ToolCategory[] = [
  { id: "media", name: "Image & Media", description: "Convert, compress and edit images, audio and video without uploading them." },
  { id: "developer", name: "Developer", description: "Encoders, formatters and inspectors for everyday development work." },
  { id: "text", name: "Text", description: "Count, compare, transform and clean up text." },
  { id: "generators", name: "Generators", description: "Passwords, QR codes, random numbers and placeholder text." },
  { id: "calculators", name: "Calculators", description: "Quick answers for money, health, math and measurements." },
  { id: "design", name: "Color & Design", description: "Pick colors, build palettes and generate CSS." },
  { id: "time", name: "Time & Date", description: "Timers, timestamps, time zones and date math." },
  { id: "device", name: "Device Tests", description: "Check your keyboard, mouse, controller, camera, mic and screen." },
  { id: "network", name: "Network", description: "IP addresses, DNS records and subnets." },
];

export type Tool = {
  /** Path under /tools, e.g. "image-converter" or "convert/png-to-jpg". */
  slug: string;
  name: string;
  /** One-liner for cards and search results. */
  description: string;
  /** Longer lede shown under the page heading. Defaults to `description`. */
  intro?: string;
  category: ToolCategoryId;
  icon: LucideIcon;
  keywords: string[];
  /** <title> override. Defaults to "<name> | Free Online Tool | Parcoil". */
  title?: string;
  /** Meta description override. Defaults to `intro` or `description`. */
  metaDescription?: string;
  /** Shown in the navbar tools menu. */
  featured?: boolean;
  /** Reachable and in the sitemap, but not listed in the directory grid. */
  hidden?: boolean;
};

const conversionTools: Tool[] = IMAGE_CONVERSIONS.map((conversion) => {
  const from = SOURCE_FORMAT_LABELS[conversion.from];
  const to = IMAGE_FORMATS[conversion.to].label;
  return {
    slug: `convert/${conversionSlug(conversion)}`,
    name: `${from} to ${to} Converter`,
    description: `Convert ${from} images to ${to} in your browser`,
    intro: `Convert ${from} images to ${to} for free. Your files are converted right on your device and are never uploaded to a server. Convert in bulk and download everything as a ZIP.`,
    title: `${from} to ${to} Converter | Free, Private & No Upload | Parcoil`,
    category: "media",
    icon: FileImage,
    keywords: [
      `${from} to ${to}`,
      `convert ${from} to ${to}`,
      `${from} to ${to} converter`,
      `${from.toLowerCase()} to ${to.toLowerCase()} online`,
      "image converter",
      "offline image converter",
    ],
    hidden: true,
  };
});

export const tools: Tool[] = [
  // Image & Media
  {
    slug: "image-converter",
    name: "Image Converter",
    description: "Convert between PNG, JPG, WebP, AVIF, GIF, BMP and ICO",
    intro: "Convert images between PNG, JPG, WebP, AVIF, GIF, BMP and ICO. Everything happens on your device, so your photos are never uploaded. Convert in bulk and download as a ZIP.",
    title: "Image Converter | PNG, JPG, WebP, AVIF, ICO | No Upload | Parcoil",
    category: "media",
    icon: Images,
    keywords: ["image converter", "convert image", "png to jpg", "jpg to png", "webp converter", "avif converter", "batch image converter", "offline image converter"],
    featured: true,
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description: "Shrink JPG, PNG and WebP file sizes without uploading",
    intro: "Reduce image file sizes for the web, email or social media. Adjust quality and dimensions and compare the results before you download. Nothing leaves your device.",
    title: "Image Compressor | Reduce Image File Size Online | Parcoil",
    category: "media",
    icon: Shrink,
    keywords: ["image compressor", "compress image", "reduce image size", "compress jpg", "compress png", "image optimizer", "shrink image"],
    featured: true,
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    description: "Resize, rotate and flip images by pixels or percentage",
    intro: "Resize images to exact pixel dimensions or by percentage, then rotate or flip them. Works in bulk and runs entirely in your browser.",
    title: "Image Resizer | Resize, Rotate & Flip Images Online | Parcoil",
    category: "media",
    icon: Scaling,
    keywords: ["image resizer", "resize image", "resize photo", "rotate image", "flip image", "change image dimensions", "bulk image resize"],
  },
  {
    slug: "image-cropper",
    name: "Image Cropper",
    description: "Crop images freely or to a fixed aspect ratio",
    intro: "Crop an image by dragging a selection or typing exact values. Lock to common aspect ratios like 1:1, 16:9 or 4:5 for social media.",
    title: "Image Cropper | Crop Images Online to Any Aspect Ratio | Parcoil",
    category: "media",
    icon: Crop,
    keywords: ["image cropper", "crop image", "crop photo online", "crop to square", "aspect ratio crop", "crop picture"],
  },
  {
    slug: "favicon-generator",
    name: "Favicon Generator",
    description: "Turn any image into favicon.ico and app icons",
    intro: "Create a favicon.ico plus PNG icons for browsers, iOS and Android from a single image. Download everything as a ZIP along with the HTML to paste into your site.",
    title: "Favicon Generator | Create favicon.ico from PNG or JPG | Parcoil",
    category: "media",
    icon: AppWindow,
    keywords: ["favicon generator", "favicon.ico", "png to ico", "create favicon", "apple touch icon", "website icon generator"],
  },
  {
    slug: "image-to-base64",
    name: "Image to Base64",
    description: "Encode images as Base64 data URIs for HTML and CSS",
    intro: "Convert an image into a Base64 data URI, ready to paste into HTML, CSS or JSON. You can also decode a Base64 string back into an image.",
    title: "Image to Base64 Converter | Data URI Generator | Parcoil",
    category: "media",
    icon: FileCode,
    keywords: ["image to base64", "base64 image", "data uri", "base64 to image", "png to base64", "embed image css"],
  },
  {
    slug: "exif-remover",
    name: "EXIF Viewer & Remover",
    description: "See hidden photo metadata like GPS location and strip it",
    intro: "Photos can carry hidden metadata such as your GPS location, camera model and the time they were taken. See what your photos reveal and remove it before sharing.",
    title: "EXIF Viewer & Remover | Remove Photo Metadata & GPS | Parcoil",
    category: "media",
    icon: EyeOff,
    keywords: ["exif remover", "remove exif", "exif viewer", "remove metadata from photo", "remove gps from photo", "photo metadata"],
  },
  {
    slug: "metadata-editor",
    name: "Photo Metadata Editor",
    description: "Add a title, tags, copyright, date taken or GPS location to photos",
    intro: "Add or edit photo metadata: title, description, tags, rating, author, copyright, camera details, date taken and GPS location. Edit one photo or many at once. Images aren't re-compressed or uploaded.",
    title: "Photo Metadata Editor | Add EXIF, Copyright, Date & GPS | Parcoil",
    category: "media",
    icon: FilePen,
    keywords: ["exif editor", "photo metadata editor", "add metadata to photo", "edit exif", "add copyright to photo", "change date taken", "add gps to photo", "geotag photo", "image tags"],
  },
  {
    slug: "image-color-picker",
    name: "Image Color Picker",
    description: "Pick colors from an image and extract its palette",
    intro: "Upload an image to pick any pixel's color and automatically extract its dominant color palette as HEX, RGB and HSL.",
    title: "Image Color Picker | Get Colors & Palette from an Image | Parcoil",
    category: "media",
    icon: Pipette,
    keywords: ["image color picker", "color picker from image", "get color from image", "extract color palette", "hex from image"],
  },
  {
    slug: "audio-converter",
    name: "Audio Converter",
    description: "Convert audio files to MP3 or WAV in your browser",
    intro: "Convert MP3, WAV, OGG, FLAC, M4A and more to MP3 or WAV. Trim the start and end and pick a bitrate. Your audio stays on your device.",
    title: "Audio Converter | Convert to MP3 or WAV Online | No Upload | Parcoil",
    category: "media",
    icon: AudioLines,
    keywords: ["audio converter", "convert to mp3", "wav to mp3", "mp3 to wav", "flac to mp3", "m4a to mp3", "ogg to mp3"],
    featured: true,
  },
  {
    slug: "video-to-mp3",
    name: "Video to MP3",
    description: "Extract the audio track from a video as MP3 or WAV",
    intro: "Pull the audio out of MP4, WebM or MOV videos and save it as MP3 or WAV. The video is processed locally and never uploaded.",
    title: "Video to MP3 Converter | Extract Audio from Video | Parcoil",
    category: "media",
    icon: FileAudio,
    keywords: ["video to mp3", "mp4 to mp3", "extract audio from video", "webm to mp3", "mov to mp3", "video to audio"],
  },
  {
    slug: "video-to-gif",
    name: "Video to GIF",
    description: "Turn a video clip into an animated GIF",
    intro: "Make an animated GIF from any MP4, WebM or MOV clip. Pick the start time, length, size and frame rate. The GIF is made on your device.",
    title: "Video to GIF Converter | MP4 to GIF Online | Parcoil",
    category: "media",
    icon: Film,
    keywords: ["video to gif", "mp4 to gif", "gif maker", "make gif from video", "webm to gif", "convert video to gif"],
  },
  ...conversionTools,

  // Developer
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON data",
    intro: "Format, validate, and minify JSON data with ease. Perfect for developers working with APIs, configuration files, and data interchange.",
    title: "JSON Formatter Tool | Format, Validate and Minify JSON Online",
    metaDescription: "Free online JSON formatter to beautify, validate, and minify JSON data. Perfect for developers working with APIs and data.",
    category: "developer",
    icon: Braces,
    keywords: ["json formatter", "json validator", "json beautifier", "json minifier", "format json", "validate json", "online json tool"],
    featured: true,
  },
  {
    slug: "json-csv",
    name: "JSON ⇄ CSV Converter",
    description: "Convert JSON arrays to CSV spreadsheets and back",
    intro: "Convert a JSON array of objects into CSV for Excel or Google Sheets, or turn a CSV file into JSON. Nested objects are flattened automatically.",
    title: "JSON to CSV Converter | CSV to JSON Online | Parcoil",
    category: "developer",
    icon: Sheet,
    keywords: ["json to csv", "csv to json", "json csv converter", "convert json to excel", "csv parser"],
  },
  {
    slug: "json-yaml",
    name: "JSON ⇄ YAML Converter",
    description: "Convert between JSON and YAML",
    intro: "Convert JSON to YAML for config files like Docker Compose and Kubernetes, or YAML back to JSON. Errors point to the exact line.",
    title: "JSON to YAML Converter | YAML to JSON Online | Parcoil",
    category: "developer",
    icon: FileJson,
    keywords: ["json to yaml", "yaml to json", "yaml converter", "yaml validator", "yml to json"],
  },
  {
    slug: "base64",
    name: "Base64 Encoder/Decoder",
    description: "Encode and decode text to Base64 format instantly",
    intro: "Easily convert your text to Base64 encoding or decode Base64 back to plain text. Supports Unicode and URL-safe Base64, and runs entirely in your browser.",
    title: "Base64 Encoder/Decoder Tool | Convert Text to Base64 and Back",
    metaDescription: "Free online tool to encode text to Base64 and decode Base64 to text. Supports Unicode and URL-safe Base64. Instant results in your browser.",
    category: "developer",
    icon: FileDigit,
    keywords: ["base64 encoder", "base64 decoder", "encode to base64", "decode base64", "online base64 tool", "text to base64", "base64 to text"],
  },
  {
    slug: "url-encoder",
    name: "URL Encoder/Decoder",
    description: "Encode and decode URLs for safe transmission",
    intro: "Encode URLs to make them safe for transmission or decode percent-encoded URLs back to their original form. All processing happens in your browser.",
    title: "URL Encoder/Decoder Tool | Encode and Decode URLs Online",
    metaDescription: "Free online tool to encode and decode URLs. Convert special characters to percent-encoded format and back.",
    category: "developer",
    icon: LinkIcon,
    keywords: ["url encoder", "url decoder", "encode url", "decode url", "percent encoding", "url encoding", "online url tool"],
  },
  {
    slug: "url-parser",
    name: "URL Parser",
    description: "Break a URL into its parts and query parameters",
    intro: "Paste any URL to see its protocol, host, port, path, hash and a decoded table of query parameters. Edit parameters and rebuild the URL.",
    title: "URL Parser | Split URL & Query String Parameters | Parcoil",
    category: "developer",
    icon: SearchCode,
    keywords: ["url parser", "query string parser", "parse url", "url params", "decode query string", "url splitter"],
  },
  {
    slug: "html-entities",
    name: "HTML Entity Encoder",
    description: "Escape and unescape HTML entities",
    intro: "Escape special characters like <, > and & into HTML entities, or decode entities back into readable text.",
    title: "HTML Entity Encoder/Decoder | Escape & Unescape HTML | Parcoil",
    category: "developer",
    icon: CodeXml,
    keywords: ["html entities", "html encoder", "html decoder", "escape html", "unescape html", "html special characters"],
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode JSON Web Tokens and inspect their claims",
    intro: "Paste a JSON Web Token to decode its header and payload, check when it expires and read standard claims. Tokens never leave your browser.",
    title: "JWT Decoder | Decode & Inspect JSON Web Tokens | Parcoil",
    category: "developer",
    icon: KeyRound,
    keywords: ["jwt decoder", "decode jwt", "jwt parser", "json web token", "jwt debugger", "jwt expiration"],
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, SHA-512 hashes",
    intro: "Generate MD5, SHA-1, SHA-256, SHA-384 and SHA-512 hashes from text or files. All hashing is done securely in your browser.",
    title: "Hash Generator Tool | Generate MD5, SHA-1, SHA-256, SHA-384, SHA-512 Hashes",
    metaDescription: "Free online hash generator for MD5, SHA-1, SHA-256, SHA-384, and SHA-512. Hash text or files securely in your browser.",
    category: "developer",
    icon: Hash,
    keywords: ["hash generator", "md5 hash", "sha1 hash", "sha256 hash", "sha384 hash", "sha512 hash", "file checksum", "online hash tool"],
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUID v4 and time-ordered v7 identifiers",
    intro: "Generate random UUIDs (Universally Unique Identifiers) instantly, one at a time or in bulk. Supports v4 and time-ordered v7.",
    title: "UUID Generator Tool | Generate Random UUIDs Online",
    metaDescription: "Free online UUID generator. Generate version 4 and version 7 UUIDs instantly, in bulk. Perfect for developers, databases, and unique identifiers.",
    category: "developer",
    icon: Fingerprint,
    keywords: ["uuid generator", "guid generator", "unique identifier", "random uuid", "uuid v4", "uuid v7", "online uuid tool"],
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions with live match highlighting",
    intro: "Write a JavaScript regular expression and see matches highlighted live, with capture groups and a replace preview.",
    title: "Regex Tester | Test Regular Expressions Online | Parcoil",
    category: "developer",
    icon: Regex,
    keywords: ["regex tester", "regular expression tester", "regex online", "javascript regex", "regex match", "regex replace"],
  },
  {
    slug: "number-base-converter",
    name: "Number Base Converter",
    description: "Convert between binary, octal, decimal and hex",
    intro: "Convert numbers between binary, octal, decimal, hexadecimal and any base from 2 to 36. Handles arbitrarily large integers.",
    title: "Number Base Converter | Binary, Hex, Decimal, Octal | Parcoil",
    category: "developer",
    icon: Sigma,
    keywords: ["base converter", "binary to decimal", "decimal to hex", "hex to decimal", "binary converter", "octal converter"],
  },
  {
    slug: "chmod-calculator",
    name: "Chmod Calculator",
    description: "Work out Linux file permissions in numeric and symbolic form",
    intro: "Tick read, write and execute permissions for owner, group and others to get the chmod number and symbolic notation, or type a number to decode it.",
    title: "Chmod Calculator | Linux File Permissions | Parcoil",
    category: "developer",
    icon: FileLock,
    keywords: ["chmod calculator", "chmod 755", "linux permissions", "unix file permissions", "chmod generator", "rwx calculator"],
  },
  {
    slug: "cron-parser",
    name: "Cron Expression Parser",
    description: "Explain cron schedules in plain English",
    intro: "Paste a cron expression to get a plain-English explanation and the next times it will run in your time zone.",
    title: "Cron Expression Parser | Explain Cron Schedules | Parcoil",
    category: "developer",
    icon: CalendarClock,
    keywords: ["cron parser", "cron expression", "crontab guru", "cron schedule", "cron explainer", "cron next run"],
  },
  {
    slug: "bios-password",
    name: "BIOS Password Recovery",
    description: "Recover forgotten BIOS/UEFI master passwords from a challenge code",
    intro: "Recover the master/recovery password for a locked BIOS/UEFI from the challenge code, service tag or serial it shows. Supports ASUS, Dell, Fujitsu-Siemens, HP/Compaq, Insyde, Phoenix, Samsung and Sony. Everything runs in your browser and is never uploaded.",
    title: "BIOS Password Recovery | Unlock Forgotten BIOS/UEFI Passwords | Parcoil",
    category: "developer",
    icon: KeyRound,
    keywords: ["bios password", "uefi password", "bios password recovery", "bios master password", "bios unlock", "reset bios password", "bios backdoor password", "laptop bios password", "dell bios password", "dell service tag password"],
  },

  // Text
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, and lines",
    intro: "Count words, characters, sentences and paragraphs with real-time updates, plus reading and speaking time. Perfect for writers, students, and anyone who needs to track text statistics.",
    title: "Word Counter Tool | Count Words, Characters, and Lines Online",
    metaDescription: "Free online word counter tool. Count words, characters (with and without spaces), sentences, paragraphs and lines in your text instantly.",
    category: "text",
    icon: FileText,
    keywords: ["word counter", "character counter", "line counter", "text counter", "word count tool", "character count", "online counter"],
    featured: true,
  },
  {
    slug: "text-case-converter",
    name: "Text Case Converter",
    description: "Convert text to uppercase, lowercase, camelCase, and more",
    intro: "Convert text between different cases: uppercase, lowercase, title case, camel case, snake case, and more.",
    title: "Text Case Converter | Free Online Tool | Parcoil",
    metaDescription: "Convert text between different cases: uppercase, lowercase, title case, camel case, snake case, and more with this free online tool.",
    category: "text",
    icon: Type,
    keywords: ["text case converter", "uppercase converter", "lowercase converter", "title case converter", "camel case converter", "snake case converter", "kebab case converter", "text transformation tool"],
  },
  {
    slug: "text-diff",
    name: "Diff Checker",
    description: "Compare two texts and highlight the differences",
    intro: "Paste two versions of a text to see exactly what was added, removed or changed, line by line and word by word.",
    title: "Diff Checker | Compare Text Online | Parcoil",
    category: "text",
    icon: Diff,
    keywords: ["diff checker", "text compare", "compare text", "diff tool", "text difference", "compare two files"],
  },
  {
    slug: "line-tools",
    name: "Sort & Dedupe Lines",
    description: "Sort, deduplicate, reverse, shuffle and clean up lines",
    intro: "Remove duplicate lines, sort alphabetically or numerically, reverse, shuffle, trim whitespace and delete empty lines in one click.",
    title: "Remove Duplicate Lines & Sort Text Online | Parcoil",
    category: "text",
    icon: ArrowDownAZ,
    keywords: ["remove duplicate lines", "sort lines", "sort alphabetically", "dedupe list", "remove empty lines", "shuffle lines"],
  },
  {
    slug: "find-replace",
    name: "Find and Replace",
    description: "Find and replace text with optional regex support",
    intro: "Search and replace text in bulk with case-sensitive, whole-word and regular expression options.",
    title: "Find and Replace Text Online | Regex Supported | Parcoil",
    category: "text",
    icon: Replace,
    keywords: ["find and replace", "replace text online", "text replacer", "regex replace", "bulk replace"],
  },
  {
    slug: "fancy-text",
    name: "Fancy Text Generator",
    description: "Turn text into 𝐛𝐨𝐥𝐝, 𝒾𝓉𝒶𝓁𝒾𝒸, 𝔤𝔬𝔱𝔥𝔦𝔠 and other Unicode styles",
    intro: "Type once and copy your text in dozens of Unicode styles for Instagram bios, Discord, TikTok and anywhere else that doesn't support formatting.",
    title: "Fancy Text Generator | Cool Fonts to Copy & Paste | Parcoil",
    category: "text",
    icon: Sparkles,
    keywords: ["fancy text generator", "cool fonts", "font generator", "bold text generator", "cursive text", "instagram fonts", "discord fonts"],
  },
  {
    slug: "morse-code",
    name: "Morse Code Translator",
    description: "Translate text to Morse code and back, with audio",
    intro: "Translate text into Morse code or decode Morse back into text, then listen to it played as audio.",
    title: "Morse Code Translator | Text to Morse with Audio | Parcoil",
    category: "text",
    icon: Radio,
    keywords: ["morse code translator", "text to morse", "morse to text", "morse code decoder", "morse code audio"],
  },
  {
    slug: "text-to-binary",
    name: "Text to Binary",
    description: "Convert text to binary, hex, octal or decimal and back",
    intro: "Convert text into binary, hexadecimal, octal or decimal byte values, or decode them back into text. Supports full Unicode via UTF-8.",
    title: "Text to Binary Converter | Binary to Text | Parcoil",
    category: "text",
    icon: Binary,
    keywords: ["text to binary", "binary to text", "binary translator", "text to hex", "hex to text", "ascii to binary"],
  },
  {
    slug: "slug-generator",
    name: "Slug Generator",
    description: "Turn titles into clean, URL-friendly slugs",
    intro: "Convert titles and phrases into clean URL slugs. Accents are removed, and you can pick the separator and casing.",
    title: "URL Slug Generator | Convert Title to Slug | Parcoil",
    category: "text",
    icon: Link2,
    keywords: ["slug generator", "url slug", "slugify", "permalink generator", "seo friendly url"],
  },
  {
    slug: "markdown-preview",
    name: "Markdown Editor",
    description: "Write Markdown with a live preview and export HTML",
    intro: "Write Markdown with a live preview, including GitHub-style tables and task lists. Copy the generated HTML or download it.",
    title: "Markdown Editor & Previewer | Markdown to HTML | Parcoil",
    category: "text",
    icon: PenLine,
    keywords: ["markdown editor", "markdown preview", "markdown to html", "online markdown", "md viewer"],
  },

  // Generators
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Create strong, secure passwords with customizable options",
    intro: "Create strong, unique passwords to protect your online accounts. Customize length and character types to match any security requirement.",
    title: "Secure Password Generator | Free Online Tool | Parcoil",
    metaDescription: "Create strong, unique passwords instantly with Parcoil's free password generator tool. Customize length and character types for maximum security.",
    category: "generators",
    icon: LockKeyhole,
    keywords: ["password generator", "secure password", "strong password", "random password generator", "passphrase generator", "online security tool"],
    featured: true,
  },
  {
    slug: "qr-code",
    name: "QR Code Generator",
    description: "Generate QR codes for URLs, text, Wi-Fi and more",
    intro: "Create QR codes for links, text, Wi-Fi networks, email and phone numbers. Customize colors and size, and download as PNG or SVG.",
    title: "QR Code Generator | Free Online Tool | Parcoil",
    metaDescription: "Create QR codes instantly for URLs, text, Wi-Fi, email and phone numbers. Customize colors and download PNG or SVG. Generated in your browser.",
    category: "generators",
    icon: QrCode,
    keywords: ["qr code generator", "create qr code", "free qr code", "wifi qr code", "online qr code tool", "url to qr code", "text to qr code"],
    featured: true,
  },
  {
    slug: "random-number",
    name: "Random Number Generator",
    description: "Pick random numbers in any range, with or without repeats",
    intro: "Generate one or many random numbers between any two values, with optional unique results and sorting. Uses your browser's cryptographic random generator.",
    title: "Random Number Generator | Pick a Number | Parcoil",
    category: "generators",
    icon: Target,
    keywords: ["random number generator", "rng", "pick a random number", "number picker", "random number between"],
  },
  {
    slug: "random-picker",
    name: "Random Name Picker",
    description: "Pick a random winner or shuffle a list of names",
    intro: "Paste a list of names or options and pick one or more at random, or shuffle the whole list into teams. Great for giveaways and classrooms.",
    title: "Random Name Picker | Pick a Winner from a List | Parcoil",
    category: "generators",
    icon: Shuffle,
    keywords: ["random name picker", "random picker", "pick a winner", "giveaway picker", "team generator", "list randomizer"],
  },
  {
    slug: "dice-roller",
    name: "Dice Roller & Coin Flip",
    description: "Roll any number of dice or flip a coin",
    intro: "Roll D4, D6, D8, D10, D12, D20 and D100 dice or flip a coin. Keep a history of your results.",
    title: "Dice Roller & Coin Flip | Roll Dice Online | Parcoil",
    category: "generators",
    icon: Dices,
    keywords: ["dice roller", "roll dice", "coin flip", "flip a coin", "d20 roller", "virtual dice"],
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder paragraphs, sentences or words",
    intro: "Generate classic Lorem Ipsum placeholder text by paragraphs, sentences or words, optionally wrapped in HTML tags.",
    title: "Lorem Ipsum Generator | Placeholder Text | Parcoil",
    category: "generators",
    icon: Pilcrow,
    keywords: ["lorem ipsum generator", "placeholder text", "dummy text", "lorem ipsum", "filler text"],
  },

  // Calculators
  {
    slug: "unit-converter",
    name: "Unit Converter",
    description: "Convert length, weight, temperature, volume, and more",
    intro: "Convert between units of length, weight, temperature, volume, area, speed, time, data, pressure and energy. Fast, accurate conversions with no sign-up required.",
    title: "Unit Converter Tool | Convert Length, Weight, Temperature Units",
    metaDescription: "Free online unit converter for length, weight, temperature, volume, area, speed, time, data storage, pressure and energy.",
    category: "calculators",
    icon: Ruler,
    keywords: ["unit converter", "length converter", "weight converter", "temperature converter", "measurement converter", "online converter"],
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Percent of a number, percent change and discounts",
    intro: "Work out what X% of a number is, what percentage one number is of another, percentage increase or decrease, and sale prices after a discount.",
    title: "Percentage Calculator | Percent Change & Discount | Parcoil",
    category: "calculators",
    icon: Percent,
    keywords: ["percentage calculator", "percent calculator", "percentage change", "percent increase", "discount calculator", "what percent of"],
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate body mass index in metric or imperial units",
    intro: "Calculate your body mass index (BMI) in metric or imperial units and see which range it falls into.",
    title: "BMI Calculator | Body Mass Index | Metric & Imperial | Parcoil",
    category: "calculators",
    icon: HeartPulse,
    keywords: ["bmi calculator", "body mass index", "calculate bmi", "bmi chart", "healthy weight calculator"],
  },
  {
    slug: "tip-calculator",
    name: "Tip Calculator",
    description: "Work out the tip and split the bill",
    intro: "Calculate the tip on a bill and split the total between any number of people, with optional rounding.",
    title: "Tip Calculator | Split the Bill | Parcoil",
    category: "calculators",
    icon: Receipt,
    keywords: ["tip calculator", "split bill", "gratuity calculator", "bill splitter", "how much to tip"],
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    description: "Monthly payments, total interest and amortization",
    intro: "Estimate the monthly payment for a mortgage, car loan or personal loan, and see the total interest and a year-by-year amortization schedule.",
    title: "Loan Calculator | Mortgage & Car Loan Payments | Parcoil",
    category: "calculators",
    icon: Landmark,
    keywords: ["loan calculator", "mortgage calculator", "monthly payment calculator", "car loan calculator", "amortization schedule", "interest calculator"],
  },
  {
    slug: "roman-numerals",
    name: "Roman Numeral Converter",
    description: "Convert numbers to Roman numerals and back",
    intro: "Convert numbers from 1 to 3,999 into Roman numerals, or decode Roman numerals back into numbers.",
    title: "Roman Numeral Converter | Numbers to Roman Numerals | Parcoil",
    category: "calculators",
    icon: Scroll,
    keywords: ["roman numeral converter", "roman numerals", "number to roman numerals", "roman numerals to numbers", "roman numeral translator"],
  },
  {
    slug: "aspect-ratio-calculator",
    name: "Aspect Ratio Calculator",
    description: "Find matching dimensions for any aspect ratio",
    intro: "Find the aspect ratio of any width and height, or calculate a missing dimension to keep a ratio like 16:9, 4:3 or 21:9.",
    title: "Aspect Ratio Calculator | 16:9, 4:3 & Custom Ratios | Parcoil",
    category: "calculators",
    icon: Ratio,
    keywords: ["aspect ratio calculator", "16:9 calculator", "resolution calculator", "image ratio", "video aspect ratio"],
  },

  // Color & Design
  {
    slug: "color-picker",
    name: "Color Picker",
    description: "Pick colors and convert between HEX, RGB, HSL",
    intro: "Select colors visually and convert between HEX, RGB, and HSL formats. Save your favorite colors for your projects.",
    title: "Color Picker & Converter | Free Online Tool | Parcoil",
    metaDescription: "Select colors and convert between HEX, RGB, and HSL formats with this free online color picker tool. Save your favorite colors for future use.",
    category: "design",
    icon: Palette,
    keywords: ["color picker", "color converter", "hex to rgb", "rgb to hex", "hsl converter", "web design tool", "color palette"],
  },
  {
    slug: "contrast-checker",
    name: "Contrast Checker",
    description: "Check text and background colors against WCAG",
    intro: "Check whether your text and background colors have enough contrast to meet WCAG AA and AAA accessibility guidelines.",
    title: "Color Contrast Checker | WCAG AA & AAA | Parcoil",
    category: "design",
    icon: Contrast,
    keywords: ["contrast checker", "color contrast", "wcag contrast", "accessibility checker", "contrast ratio"],
  },
  {
    slug: "palette-generator",
    name: "Color Palette Generator",
    description: "Build harmonious palettes, shades and tints",
    intro: "Generate complementary, analogous, triadic and monochromatic palettes plus shades and tints from any base color. Export as CSS variables or Tailwind config.",
    title: "Color Palette Generator | Shades, Tints & Harmonies | Parcoil",
    category: "design",
    icon: SwatchBook,
    keywords: ["color palette generator", "color scheme generator", "shades generator", "tints", "complementary colors", "tailwind colors"],
  },
  {
    slug: "gradient-generator",
    name: "CSS Gradient Generator",
    description: "Design linear and radial gradients and copy the CSS",
    intro: "Design linear, radial and conic CSS gradients with any number of color stops and copy the code.",
    title: "CSS Gradient Generator | Linear, Radial & Conic | Parcoil",
    category: "design",
    icon: Blend,
    keywords: ["css gradient generator", "gradient generator", "linear gradient", "radial gradient", "background gradient css"],
  },
  {
    slug: "box-shadow-generator",
    name: "Box Shadow Generator",
    description: "Design layered CSS box shadows visually",
    intro: "Design CSS box shadows with multiple layers, inset shadows and live preview, then copy the code.",
    title: "CSS Box Shadow Generator | Parcoil",
    category: "design",
    icon: Layers,
    keywords: ["box shadow generator", "css box shadow", "shadow generator", "css shadow", "drop shadow css"],
  },

  // Time & Date
  {
    slug: "unix-timestamp",
    name: "Unix Timestamp Converter",
    description: "Convert Unix epoch timestamps to dates and back",
    intro: "Convert Unix timestamps in seconds or milliseconds to human-readable dates in UTC and your local time zone, and back again.",
    title: "Unix Timestamp Converter | Epoch to Date | Parcoil",
    category: "time",
    icon: Clock,
    keywords: ["unix timestamp converter", "epoch converter", "timestamp to date", "date to timestamp", "epoch time"],
  },
  {
    slug: "stopwatch",
    name: "Stopwatch",
    description: "Online stopwatch with lap times",
    intro: "A precise online stopwatch with lap and split times. Use the space bar to start and stop.",
    title: "Online Stopwatch with Laps | Parcoil",
    category: "time",
    icon: Timer,
    keywords: ["online stopwatch", "stopwatch", "lap timer", "stop watch", "timer with laps"],
  },
  {
    slug: "countdown-timer",
    name: "Countdown Timer",
    description: "Set a timer with an alarm sound",
    intro: "Set a countdown timer for any length of time and get an alarm when it finishes. Quick presets for common durations.",
    title: "Online Countdown Timer with Alarm | Parcoil",
    category: "time",
    icon: AlarmClock,
    keywords: ["countdown timer", "online timer", "timer with alarm", "5 minute timer", "10 minute timer", "kitchen timer"],
  },
  {
    slug: "timezone-converter",
    name: "Time Zone Converter",
    description: "Convert a time between cities and time zones",
    intro: "Convert a date and time between time zones around the world. Daylight saving time is handled automatically.",
    title: "Time Zone Converter | World Clock | Parcoil",
    category: "time",
    icon: Earth,
    keywords: ["time zone converter", "timezone converter", "world clock", "est to pst", "utc converter", "meeting planner"],
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Exact age in years, months and days",
    intro: "Calculate exact age in years, months and days from a date of birth, plus the total days lived and when the next birthday is.",
    title: "Age Calculator | How Old Am I? | Parcoil",
    category: "time",
    icon: Cake,
    keywords: ["age calculator", "how old am i", "calculate age", "birthday calculator", "age in days"],
  },
  {
    slug: "date-calculator",
    name: "Date Calculator",
    description: "Days between dates, and add or subtract days",
    intro: "Count the days, weeks and months between two dates, including business days, or add and subtract time from a date.",
    title: "Date Calculator | Days Between Dates | Parcoil",
    category: "time",
    icon: CalendarRange,
    keywords: ["date calculator", "days between dates", "day counter", "add days to date", "business days calculator", "date difference"],
  },

  // Device tests
  {
    slug: "gamepad-tester",
    name: "Gamepad Tester",
    description: "Test your gamepad buttons, sticks, and triggers in real time",
    intro: "Connect a gamepad via USB or Bluetooth, press a button, and see all your controller inputs in real time. No downloads required.",
    title: "Gamepad Tester | Test Your Controller Online | Parcoil",
    metaDescription: "Test your gamepad or controller online with Parcoil's free gamepad tester. Check buttons, triggers, and analog sticks in real time.",
    category: "device",
    icon: Gamepad2,
    keywords: ["gamepad tester", "controller tester", "gamepad test", "xbox controller", "ps4 controller", "ps5 controller", "nintendo switch controller", "online gamepad test"],
  },
  {
    slug: "keyboard-tester",
    name: "Keyboard Tester",
    description: "Check every key on your keyboard works",
    intro: "Press keys to see them light up on a virtual keyboard. Find dead keys, stuck keys and ghosting issues without installing anything.",
    title: "Keyboard Tester | Test Keys Online | Parcoil",
    category: "device",
    icon: Keyboard,
    keywords: ["keyboard tester", "keyboard test", "key tester", "test keyboard online", "keyboard ghosting test", "n-key rollover test"],
  },
  {
    slug: "mouse-tester",
    name: "Mouse Tester",
    description: "Test mouse buttons, scroll wheel and double-clicks",
    intro: "Check that every mouse button, the scroll wheel and double-clicking work properly, and catch accidental double-clicks from a worn switch.",
    title: "Mouse Tester | Test Mouse Buttons & Double Click | Parcoil",
    category: "device",
    icon: Mouse,
    keywords: ["mouse tester", "mouse test", "double click test", "mouse button test", "scroll wheel test"],
  },
  {
    slug: "cps-test",
    name: "Click Speed Test",
    description: "How many clicks per second can you do?",
    intro: "Measure how many times you can click per second (CPS). Pick a test length and try to beat your best score.",
    title: "CPS Test | Click Speed Test | Parcoil",
    category: "device",
    icon: MousePointerClick,
    keywords: ["cps test", "click speed test", "clicks per second", "click test", "jitter click test"],
  },
  {
    slug: "typing-test",
    name: "Typing Speed Test",
    description: "Measure your words per minute and accuracy",
    intro: "Find out how fast you type in words per minute (WPM) and how accurate you are with a quick timed test.",
    title: "Typing Speed Test | WPM Test | Parcoil",
    category: "device",
    icon: TextCursorInput,
    keywords: ["typing test", "typing speed test", "wpm test", "words per minute", "typing speed"],
  },
  {
    slug: "reaction-time-test",
    name: "Reaction Time Test",
    description: "Test how fast you react in milliseconds",
    intro: "Click as soon as the screen turns green to measure your reaction time in milliseconds. Average your results over several tries.",
    title: "Reaction Time Test | Parcoil",
    category: "device",
    icon: Zap,
    keywords: ["reaction time test", "reaction test", "reflex test", "human benchmark", "reaction speed"],
  },
  {
    slug: "webcam-test",
    name: "Webcam Test",
    description: "Check your camera works and see its resolution",
    intro: "Check that your webcam works, see which resolution and frame rate it supports and take a snapshot. The video never leaves your device.",
    title: "Webcam Test | Check Your Camera Online | Parcoil",
    category: "device",
    icon: Camera,
    keywords: ["webcam test", "camera test", "test my webcam", "online camera", "webcam resolution"],
  },
  {
    slug: "mic-test",
    name: "Microphone Test",
    description: "Check your mic level and record a sample",
    intro: "Check that your microphone works with a live volume meter and waveform, and record a short clip to hear how you sound.",
    title: "Mic Test | Test Your Microphone Online | Parcoil",
    category: "device",
    icon: Mic,
    keywords: ["mic test", "microphone test", "test my mic", "online mic test", "microphone check"],
  },
  {
    slug: "speaker-test",
    name: "Speaker Test",
    description: "Test left and right speakers and frequency response",
    intro: "Play sounds through your left and right speakers separately and sweep through frequencies to test your headphones or speakers.",
    title: "Speaker Test | Left Right Audio Test | Parcoil",
    category: "device",
    icon: Volume2,
    keywords: ["speaker test", "left right audio test", "stereo test", "headphone test", "sound test", "frequency test"],
  },
  {
    slug: "pixel",
    name: "Dead Pixel Test",
    description: "Cycle full-screen colors to find dead or stuck pixels",
    intro: "Test your monitor by cycling through solid full-screen colors to spot dead, stuck or hot pixels and backlight bleed.",
    title: "Dead Pixel Test | Check Your Monitor Online | Parcoil",
    category: "device",
    icon: Monitor,
    keywords: ["dead pixel test", "stuck pixel test", "monitor test", "screen test", "pixel checker", "backlight bleed test"],
  },
  {
    slug: "refresh-rate-test",
    name: "Refresh Rate Test",
    description: "Find out your screen's refresh rate in Hz",
    intro: "Measure your display's real refresh rate in Hz and check for dropped frames. Useful for confirming 120Hz, 144Hz or 240Hz monitors are set up correctly.",
    title: "Refresh Rate Test | What Hz Is My Monitor? | Parcoil",
    category: "device",
    icon: Gauge,
    keywords: ["refresh rate test", "hz test", "monitor refresh rate", "144hz test", "fps test", "frame rate test"],
  },
  {
    slug: "browser-info",
    name: "What's My Browser",
    description: "See your browser, OS, screen resolution and more",
    intro: "See your browser and version, operating system, screen resolution, viewport size, pixel ratio, language and other details your browser shares with websites.",
    title: "What Is My Screen Resolution & Browser? | Parcoil",
    category: "device",
    icon: MonitorSmartphone,
    keywords: ["what is my browser", "screen resolution", "what is my screen resolution", "user agent", "browser info", "viewport size"],
  },

  // Network
  {
    slug: "ip",
    name: "What's My IP",
    description: "View your public IP address and location details",
    intro: "View your public IPv4 and IPv6 addresses along with your approximate location, ISP and time zone.",
    title: "What's My IP Address? | IPv4 & IPv6 Lookup | Parcoil",
    metaDescription: "View your public IP address, location, and connection details instantly.",
    category: "network",
    icon: Globe,
    keywords: ["IP address", "IP lookup", "what's my IP", "my IP", "IP geolocation", "IPv6 address", "network info"],
    featured: true,
  },
  {
    slug: "dns-lookup",
    name: "DNS Lookup",
    description: "Look up A, AAAA, MX, TXT, CNAME and NS records",
    intro: "Look up DNS records for any domain, including A, AAAA, CNAME, MX, TXT, NS and CAA, using DNS over HTTPS.",
    title: "DNS Lookup | Check DNS Records Online | Parcoil",
    category: "network",
    icon: Server,
    keywords: ["dns lookup", "dns checker", "mx lookup", "txt record lookup", "nslookup online", "dns records"],
  },
  {
    slug: "subnet-calculator",
    name: "Subnet Calculator",
    description: "Calculate IPv4 network ranges from CIDR notation",
    intro: "Enter an IPv4 address and prefix to see the network address, broadcast address, usable host range, subnet mask and wildcard mask.",
    title: "Subnet Calculator | IPv4 CIDR Calculator | Parcoil",
    category: "network",
    icon: Network,
    keywords: ["subnet calculator", "cidr calculator", "ip calculator", "subnet mask", "ipv4 subnet", "network calculator"],
  },
];

export const toolHref = (tool: Tool) => `/tools/${tool.slug}`;

export function getTool(slug: string): Tool {
  const tool = tools.find((t) => t.slug === slug);
  if (!tool) throw new Error(`Unknown tool: ${slug}`);
  return tool;
}

export const getCategory = (id: ToolCategoryId) =>
  TOOL_CATEGORIES.find((c) => c.id === id)!;

export const listedTools = tools.filter((t) => !t.hidden);

export const featuredTools = tools.filter((t) => t.featured);

export const conversionToolList = tools.filter((t) => t.slug.startsWith("convert/"));

export function getRelatedTools(slug: string, limit = 6): Tool[] {
  const tool = getTool(slug);
  const sameCategory = listedTools.filter(
    (t) => t.category === tool.category && t.slug !== slug,
  );
  // Rotate the list so neighbouring tools link to different sets.
  const offset = Math.max(0, listedTools.indexOf(tool)) % Math.max(1, sameCategory.length);
  return [...sameCategory.slice(offset), ...sameCategory.slice(0, offset)].slice(0, limit);
}

export function toolMetadata(slug: string): Metadata {
  const tool = getTool(slug);
  const title = tool.title ?? `${tool.name} | Free Online Tool | ${SITE_NAME}`;
  const description = tool.metaDescription ?? tool.intro ?? tool.description;
  const url = `${SITE_URL}${toolHref(tool)}`;
  return {
    title,
    description,
    keywords: tool.keywords,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      siteName: SITE_NAME,
      type: "website",
      locale: "en_US",
    },
  };
}
